import Board from '../assets/js/board.js';

const dialog = document.getElementById('dialog');
const tpl = document.getElementById('tpl-dialog');
const board = new Board('board');
const tutorial = {
  'board/0': _=>{
    for (let x = 0; x<7;x++) {
      board.drawText(7.4 - x, 8.05, 0.5, board.color.sun, 'ABCDEFG'[x]);
      board.drawText(8.05, 7.4 - x, 0.5, board.color.sun, x.toString());
    }
    if (window.innerWidth > window.innerHeight) {
      dialog.style.top = '10%';
      dialog.style.right = '20%';
    }
    return {
      title: 'Sol',
      desc: 'Marcas: G, F, E, D, C, B, A<br>Escalas: 0, 1, 2, 3, 4, 5, 6'
    }
  },
  'board/1': _=>{
    for (let x = 0; x<7;x++) {
      board.drawText(x + 1.4, 0.5, 0.5, board.color.moon, 'ABCDEFG'[x]);
      board.drawText(0.6, 7.4 - x, 0.5, board.color.moon, (6 - x).toString());
    }
    return {
      title: 'Luna',
      desc: 'Marcas: A, B, C, D, E, F, G<br>Escalas: 0, 1, 2, 3, 4, 5, 6'
    }
  },
  'board/2': _=>{
    for (let x = 0; x<7;x++) {
      board.drawText(7.4 - x, 8.05, 0.5, board.color.sun, '1235321'[x]);
      board.drawText(8.05, 7.4 - x, 0.5, board.color.moon, x.toString());
    }
    if (window.innerWidth > window.innerHeight) {
      dialog.style.top = '10%';
      dialog.style.right = '20%';
    }
    return {
      title: 'Yupana',
      desc: 'Pesos: 1, 2, 3, 5, 3, 2, 1<br>Escalas: 0, 1, 2, 3, 4, 5, 6'
    }
  },
  'board/3': _=> {
    board.drawText(6, 6.5,1, board.color.sun, 'I', null, 'center', 'middle');
    board.drawText(2.5, 6,1, board.color.sun, 'II', null, 'center', 'middle');
    board.drawText(3, 2.5,1, board.color.sun, 'III', null, 'center', 'middle');
    board.drawText(6.5, 3,1, board.color.sun, 'IV', null, 'center', 'middle');
    board.drawText(4.5,4.6,1, board.color.sun, 'X', 'Arial', 'center', 'middle');
    board.drawSquare(4, 5, 4, 0.05, board.color.moon);
    board.drawSquare(4, 4, 0.05, 4, board.color.moon);
    board.drawSquare(1, 4, 4, 0.05, board.color.moon);
    board.drawSquare(5, 1, 0.05, 4, board.color.moon);
    if (window.innerWidth > window.innerHeight) {
      dialog.style.right = '50%';
    }
    return {
      title: 'Sectores',
      desc: ''
    }
  },
  'pieces/0': _=>{
    board.set(board.base64ToBits(
      'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAEAAAAAAAEAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='
    ));
    if (window.innerWidth > window.innerHeight) {
      dialog.style.right = '40%';
    }
    return {
      title: 'Persona',
      desc: ''
    }
  },
  'pieces/1': _=>{
    board.set(board.base64ToBits(
      'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAABAAAAAQAAAAEAAAAAAAEAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='
    ));
    if (window.innerWidth > window.innerHeight) {
      dialog.style.right = '40%';
    }
    return {
      title: 'Militar',
      desc: ''
    }
  },
  'pieces/2': _=>{ 
    board.set(board.base64ToBits(
      'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='
    ));
    if (window.innerWidth > window.innerHeight) {
      dialog.style.top = '20%';
      dialog.style.right = '50%';
    }
    return {
      title: 'Estatal',
      desc: '(*) Puede ser hacia <br>la derecha o la izquierda.'
    }
  },
  'pieces/3': _=>{
    board.set(board.base64ToBits(
      'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQABAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='
    ));
    return {
      title: 'Ataque',
      desc: 'Luna ataca reemplazando la posición de Sol.'
    }
  },
  'pieces/4': _=>{
    board.set(board.base64ToBits(
      'AAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAQABAQABAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='
    ));
    return {
      title: 'Derribo',
      desc: 'Mientras se ocupa el centro, solo se permiten derribos a las piezas en medio del rival.'
    }
  },
  'squares/0': _=> {
    board.set(board.base64ToBits(
      'AAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQA='
    ));
    if (window.innerWidth > window.innerHeight) {
      dialog.style.top = '10%';
    }
    return {
      title: 'Borde',
      desc: ''
    }
  },
  'squares/1': _=> { 
    board.set(board.base64ToBits(
      'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAAAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='
    ));
    if (window.innerWidth > window.innerHeight) {
      dialog.style.right = '40%';
    }
    return {
      title: 'Continente',
      desc: ''
    }
  },
  'squares/2': _=> {
    board.set(board.base64ToBits(
      'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='
    ));
    return {
      title: 'Centro',
      desc: ''
    }
  },
  'squares/3': _=> {
    board.set(board.base64ToBits(
      'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='
    ));
    return {
      title: 'Sierra',
      desc: ''
    }
  },
  'squares/4': _=> {
    board.set(board.base64ToBits(
      'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='
    ));
    if (window.innerWidth > window.innerHeight) {
      dialog.style.right = '40%';
    }
    return {
      title: 'Selva',
      desc: ''
    }
  },
  'squares/5': _=> {
    board.set(board.base64ToBits(
      'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAA='
    ));
    if (window.innerWidth > window.innerHeight) {
      dialog.style.top = '10%';
    }
    return {
      title: 'Costa',
      desc: ''
    }
  },
  'squares/6': _=> {    
    board.set(board.base64ToBits(
      'AAAAAAAAAAAAAAAAAAABAAAAAAAAAQAAAAAAAAAAAAAAAAABAAAAAAAAAQAAAAAAAAAAAAAAAAABAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAQAAAAAAAAAAAAAAAAABAAAAAAAAAQAAAAAAAAAAAAAAAAABAAAAAAAAAQAAAAAAAAA='
    ));
    if (window.innerWidth > window.innerHeight) {
      dialog.style.top = '10%';
    }
    return {
      title: 'Océano',
      desc: ''
    }
  },
  'squares/7': _=> {    
    board.set(board.base64ToBits(
      'AAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE='
    ));
    if (window.innerWidth > window.innerHeight) {
      dialog.style.top = '10%';
    }
    return {
      title: 'Islas',
      desc: ''
    }
  }
};
const display = function display() {
  const hash = location.hash.slice(1);
  const tuto = tutorial[hash];
  board.resizeCanvas();
  dialog.close();
  dialog.style = {top: '', bottom: '', left: '', right: ''};
  if (tuto) {
    const clone = tpl.content.cloneNode(true);
    const data = tuto();
    clone.querySelector('h2').innerHTML = data.title;
    clone.querySelector('p').innerHTML = data.desc;
    dialog.innerHTML = '';
    dialog.appendChild(clone);
    dialog.show();
  }
  else dialog.showModal();
};
window.toNext = _=>{
  const hash = location.hash.slice(1).split('/');
  const key = hash[0] + '/' + (parseInt(hash[1]) + 1);
  location.hash = '#' + (tutorial.hasOwnProperty(key) ? key : (hash[0] + '/0'));
};
window.toPrev = _=> {
  const hash = location.hash.slice(1).split('/');
  const prev = parseInt(hash[1]) - 1;
  location.hash = '#' + hash[0] + '/' + (prev < 0 ? 0 : prev);
};

board.makeCanvas();

window.addEventListener('keydown', event=> {
  if (event.key === 'ArrowLeft') toPrev();
  else if (event.key === 'ArrowRight') toNext();
});
window.addEventListener('hashchange', display);
window.addEventListener('resize', display);
display();
